// <auto-generated />
using API_Placas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Placas.Migrations
{
    [DbContext(typeof(PlacaContext))]
    [Migration("20220405173025_MigracaoPlaca")]
    partial class MigracaoPlaca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("API_Placas.Models.Placa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Meio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome_Operador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome_Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantidade_Colonias")
                        .HasColumnType("int");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Placas");
                });
#pragma warning restore 612, 618
        }
    }
}
